<?php

namespace Kay313\ClearChat\commands;

use Kay313\ClearChat\Main;
use pocketmine\command\Command;
use pocketmine\command\CommandSender;
use pocketmine\player\Player;
use pocketmine\Server;
use pocketmine\utils\TextFormat;
use pocketmine\utils\Config;

class PCC extends Command
{

    public function __construct()
    {
        parent::__construct("pcc", "Clear your chat!");
    }


    public function execute(CommandSender $sender, string $commandLabel, array $args)
    {
        if ($sender instanceof Player) {
            $player = $sender;
            if (!$player->hasPermission("pcc.use")) {
                $player->sendMessage("§cYou do not have the permission to run this command!");
                return;
            }
            $player->sendMessage("§l§cYour chat will now be deleted");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§r");
            $player->sendMessage("§l§cYour chat has been deleted");
            return;
        }
        $sender->sendMessage(TextFormat::RED . "Run this command in-game!");
    }
}